//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taken_courses
    {
        public string student_id { get; set; }
        public string course_id { get; set; }
        public string result { get; set; }
        public string section { get; set; }
        public string semester { get; set; }
    
        public virtual course course { get; set; }
        public virtual Student Student { get; set; }
    }
}
